version: '3.8'
services:
  service-api:
    build: .
    env_file: .env
    ports: 
      - 8080:8080
    image: registry.punk.link/deezer-service:latest
    healthcheck:
      test: ["cmd", "deezer-service.exe"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s